server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aymen-Moulehi/Microservices
          search-paths: /setup/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
