services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: planet
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: galaxy
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: unless-stopped

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper:/var/lib/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - kafka:/var/lib/kafka
    ports:
      - "9092:9092"
    networks:
      - backend
    depends_on:
      - zookeeper
    restart: unless-stopped

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=dev
    networks:
      - backend

  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - spring.profiles.active=dev
    networks:
      - backend

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - eureka
    environment:
      - spring.profiles.active=dev
    networks:
      - backend

  galaxy:
    build:
      context: ./galaxy
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - mysql
      - keycloak
      - kafka
    environment:
      - spring.profiles.active=dev
    networks:
      - backend

  planet:
    build:
      context: ./planet
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - postgres
      - keycloak
      - kafka
    environment:
      - spring.profiles.active=dev
    networks:
      - backend

networks:
  backend:
    driver: bridge


volumes:
  mysql:
  postgres:
  keycloak_data:
  zookeeper:
  kafka:
