spring:
  datasource:
    url: # todo change the URL jdbc:mysql://localhost:3306/galaxy
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: # todo change the URL http://localhost:8080/realms/Universe
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: # todo change the URL localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: # todo change the URL http://localhost:8761/eureka/
