spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/planet
    username: root
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/Universe
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: kafka:9092